apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  # nome do deployment
  name: deploy-nginx-deployment
  namespace: elysium
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
# definindo a estrategia de update
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.3"
            memory: 64Mi