apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    fruta: banana
  # nome do deployment
  name: deploy-nginx-deployment
  namespace: elysium
spec:
  replicas: 4
  # numero maximo de revisoes
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx-deployment
# definindo a estrategia de update
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # quantos a mais pode ser atualizado
      maxSurge: 0
      # quantos pods indisponiveis
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.3"
            memory: 64Mi
        startupProbe: # Onde definimos a nossa probe de inicialização
          httpGet: # O tipo de teste que iremos executar, neste caso, iremos executar um teste HTTP
            port: 80 # A porta que iremos testar
            path: / # O caminho que iremos testar
          initialDelaySeconds: 10 # O tempo que iremos esperar para executar a primeira vez a probe
          periodSeconds: 10 # De quanto em quanto tempo iremos executar a probe
          timeoutSeconds: 5 # O tempo que iremos esperar para considerar que a probe falhou
          successThreshold: 1 # O número de vezes que a probe precisa passar para considerar que o container está pronto
          failureThreshold: 3 # O número de vezes que a probe precisa falhar para considerar que o container não está pronto
