apiVersion: apps/v1
# tipo de kind ex pod ou deployment
kind: Deployment
# dados do deployment
metadata:
  name: deploy-elysium-service
  namespace: elysium
# especificações do deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elysium-service
  # dados do pod
  template:
    metadata:
      labels:
        app: elysium-service
    # dados dos containers
    spec: 
      containers:
      - image: rodrigobiagi/elysium-aspnet:6.0
        name: elysium-aspnet
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: TZ
            value: America/Sao_Paulo
      - image: nginx
        name: elysium-nginx
        ports:
        - containerPort: 8081
        resources: {}
        env:
          - name: TZ
            value: America/Sao_Paulo

      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
