apiVersion: apps/v1
# tipo de servico ex deployment
kind: Deployment
# informacoes do deployment
metadata:
  labels:
    run: elysium-aspnet
  name: deploy-elysium-aspnet
  namespace: elysium
# especificações do deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elysium-aspnet
  template:
    metadata:
      labels:
        app: elysium-aspnet
# especificacoes do container
    spec: 
      containers:
      - image: rodrigobiagi/elysium-aspnet:6.0
        name: elysium-aspnet
        ports:
        - containerPort: 80
        resources: {}
        # parametro de timezone
        env:
          - name: TZ
            value: America/Sao_Paulo

      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
