apiVersion: v1
kind: Pod
metadata:
  labels:
    run: elysium-alpine
    service: webserver
  name: elysium-alpine
  namespace: elysium
spec:
  containers:
  - image: alpine
    name: elysium-alpine
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
