apiVersion: v1
kind: Pod
metadata:
  labels:
    run: elysium-aspnet
  name: elysium-aspnet
  namespace: elysium
spec:
  containers:
  - image: rodrigobiagi/elysium-aspnet:6.0
    name: elysium-aspnet
    volumeMounts:
    - mountPath: /elysium
      name: elysium-emptydir
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: elysium-emptydir
    emptyDir:
      sizeLimit: 250Mi
