apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elysium-aspnet
  name: elysium-aspnet
  namespace: elysium
spec:
  containers:
  - image: rodrigobiagi/elysium-aspnet:6.0
    name: elysium-aspnet
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
