apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-portal-web
  namespace: #{namespace}#
spec:
  maxReplicas: #{max-replicas}#
  minReplicas: #{min-replicas}#
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-portal-web
  targetCPUUtilizationPercentage: 50
