apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-wkr-processador-ba
  namespace: #{namespace}#
spec:
  maxReplicas: #{max-replicas}#
  minReplicas: #{min-replicas}#
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-wkr-processador-ba
  targetCPUUtilizationPercentage: 80
