apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    fruta: banana
  # nome do deployment
  name: deploy-nginx-deployment
  namespace: elysium
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx-deployment
# definindo a estrategia de update
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # quantos a mais pode ser atualizado
      maxSurge: 1
      # quantos pods indisponiveis
      maxUnavailable: 3
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources:
          limits:
            cpu: "0.9"
            memory: 256Mi
          requests:
            cpu: "0.4"
            memory: 64Mi