trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'HML'
  displayName: 'HML'
  jobs:
  - job: "HML" 
    displayName: 'HML'
    steps:
    - task: Docker@2
      displayName: 'Docker Login'
      inputs:
        containerRegistry: 'tbkacrbase001'
        command: 'login'

    - task: Bash@3
      displayName: 'Docker Build e Push'
      inputs:
        targetType: 'inline'
        script: |
          docker build -f Dockerfile -t tbkacrbase001.azurecr.io/aspnet6-tecnobank .
          docker image push tbkacrbase001.azurecr.io/aspnet6-tecnobank
